services:
  app:
    build: .  
    ports:
      - "8000:8000"
    environment:
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
    depends_on:
      - mongo
 

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"  
    volumes:
      - mongodb_data:/data/db  

volumes:
  mongodb_data:  